### ISSUE TITLE
Does it work with Visual Studio 2019 for Mac?

### ISSUE THREAD

**Issue by izotecarlitos** [syncfusion/essential-ui-kit-for-xamarin.forms#16]
Hi, 
Does this work with Visual Studio 2019 for Mac?

Thanks, 

Carlos

**Comment by MeikandaNayanar** [comment]
Hi @izotecarlitos ,

Yes, this source will work with Visual Studio for MAC. 

Please let me know if you have any questions. 

Thanks,
Meikandan

**Comment by izotecarlitos** [comment]
Great! Thanks for the prompt reply. Will the extension found in the market
place also work with VS 2019 for Mac?

**Comment by MeikandaNayanar** [comment]
Hi @izotecarlitos 

At present, we have Visual Studio extension support only for Windows. We have plans to give support for MAC by the end of this November 2019. We will update this thread once we have released the Visual Studio extension support for MAC. 

Thanks,
Meikandan

**Comment by izotecarlitos** [comment]
Excellent news!!! Still haven't decided if I will go with Xamarin or
Flutter. Syncfusion's toolset is what's really driving my decision making
with Xamarin. Hope to hear from you next month!!! Really looking forward to
it.

**Comment by Twelve57** [comment]
So, how to use it on a mac whitout the extension menu ?
Everything is installed but I still don't understand how to use it.

**Comment by MeikandaNayanar** [comment]
Hi, 
We are glad to announce that we have now published the Essential UI Kit Visual Studio extension for MAC and updated this page. 
https://www.syncfusion.com/essential-xamarin-ui-kit
You can download the Essential UI Kit Visual Studio extension for MAC from [here](https://s3.amazonaws.com/files2.syncfusion.com/general/xamarinchallenge/Syncfusion.Xamarin.Mac.UIKit_1.0.0.0.mpack), and follow [these ](https://www.syncfusion.com/kb/10877/how-to-install-extension-in-visual-studio-for-mac)instructions to install the downloaded extension in your Visual Studio for Mac.
Please let us know if you have any questions in this.
Thanks, 
Meikandan

**Comment by rekhender** [comment]
With Visual Studio 2019, i cannot find the option to add pages to my project. How do I solve this issue?
